version: "3" 
services: 
  frontend: 
    depends_on: 
      - backend 
    image: ghcr.io/int365-projectstreamingmusic/int365_frontend:latest 
    container_name: frontend-pro 
    networks: 
      - int372 
  backend: 
    container_name: backend-pro 
    image: ghcr.io/int365-projectstreamingmusic/int365-be-music-application-main:latest 
    networks: 
      - int372 
  reverse-proxy: 
    depends_on: 
      - backend 
      - frontend 
    image: nginx:1.23-alpine 
    restart: unless-stopped 
    container_name: reverse-proxy 
    volumes: 
      - ./data/reverse-proxy/nginx.conf:/etc/nginx/conf.d/default.conf 
    ports: 
      - 80:80 
    networks: 
      - int372 
  mysql_playmylist:
    container_name: database_mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: 'DatabaseAdmin'
      MYSQL_PASSWORD: 'Database@dm1n'
      MYSQL_ROOT_PASSWORD: 'Database@dm1n'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /mysql_database:/var/lib/mysql
  minio_playmylist:
    container_name: storage_minio
    image: minio/minio
    restart: always
    environment:
      MINIO_ROOT_USER: MinioAdmin
      MINIO_ROOT_PASSWORD: MInio@dm1n
    command: server /minio --console-address ":9001"
    expose:
      - '9000'
      - '9001'
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - /minio:/mini
networks: 
    int372: 
      driver: bridge 
